homete/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('front.')->group(function () {
    Route::get('/', 'FrontController@index')->name('index');
    Route::get('/about', 'FrontController@about')->name('about');
    Route::get('/rooms', 'FrontController@rooms')->name('rooms');
    Route::get('/service', 'FrontController@service')->name('service');
    Route::get('/news', 'FrontController@news')->name('news');
    Route::get('/traffic', 'FrontController@traffic')->name('traffic');

    Route::get('/login', 'FrontController@booking')->name('login');
    Route::prefix('booking')->group(function () {
        Route::get('/', 'FrontController@booking')->name('booking');
        Route::get('/{any}', 'FrontController@booking')->where('any', '.*');
    });
    Route::prefix('member')->group(function () {
        Route::get('/', 'FrontController@booking');
        Route::get('/{any}', 'FrontController@booking')->where('any', '.*');
    });

});

Route::name('backend.')->prefix('webmin')->group(function () {
    Route::get('/', 'BackendController@index')->where('any', '.*');
    Route::get('/{any}', 'BackendController@index')->where('any', '.*')->name('index');
});


Route::group(['prefix' => 'filemanager', 'middleware' => ['api']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/TEST', function(){
    \Artisan::call('storage:link');
});

homete/app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use App\Eloquents\Receiver;
use App\Formatter\FormatContract;
use App\Http\Requests\CheckingOrderRequest;
use App\Http\Requests\MemberForgetRequest;
use App\Http\Requests\MemberLoginRequest;
use App\Http\Requests\MemberRegisterRequest;
use App\Http\Requests\OrderSearchRequest;
use App\Http\Requests\RemainRequest;
use App\Http\Requests\SearchRequest;
use App\Http\Requests\UpdateMemberBasicRequest;
use App\Http\Requests\UpdateMemberEmailRequest;
use App\Http\Requests\UpdateMemberPasswordRequest;
use App\Mail\MemberForgot;
use App\Member;
use App\Repositories\ATMInfoRepository;
use App\Repositories\DiscountCodeRepository;
use App\Repositories\EmailSettingRepository;
use App\Repositories\LicenseRepository;
use App\Repositories\RoomRepository;
use App\Repositories\RuleRepository;
use App\Repositories\SettingRepository;
use App\Service\DiscountCode;
use App\Service\Email;
use App\Service\Order;
use App\Service\OrderData;
use App\Service\Remain;
use App\Service\RoomSearching;
use App\Service\RoomSearchingByRoom;
use App\Service\TransForm;
use http\Env\Response;
use Illuminate\Http\Request;

class FrontController extends Controller
{
    private $FormatContract;
    public function __construct(FormatContract $FormatContract)
    {
        $this->FormatContract = $FormatContract;
        $this->middleware('jwt.member')->only('UpdateMemberBasic');
    }

    public function index()
    {
        return view('front.home.index');
    }

    public function about()
    {
        return view('front.about.index');
    }

    public function booking()
    {
        return view('front.booking');
    }



    //Front api Response
    public function getTags()
    {
        $Tags = \App\Tag::get(['Name','IconSrc']);
        return response()->json($Tags);
    }

    public function Searching(SearchRequest $request,LicenseRepository $license)
    {
       $RoomSearching = new RoomSearching($request->StartDate,$request->EndDate,$request->Adults,$request->Childrens,$request->Babys);
       $data = $RoomSearching->ResponseData($license);
       return response()->json($data,200);
    }

    public function SearchingByRoom(Request $request,LicenseRepository $license)
    {
        $RoomSearchingByRoom = new RoomSearchingByRoom($request->Room,$request->StartDate,$request->EndDate);
        try {
            $data = $RoomSearchingByRoom->ResponseData($license);
            return response()->json($data,200);
        } catch (\Exception $e) {
            return $this->FormatContract->customError('錯誤', ['區間無空房'], 400);
        }
    }

    public function Remain(RemainRequest $request,RoomRepository $roomRepository)
    {
        $Remains = new Remain($roomRepository);
        $data = $Remains->Get($request->room,\Carbon\Carbon::parse($request->months)->startOfMonth(),\Carbon\Carbon::parse($request->months)->endOfMonth());
        $res = [];
        collect($data)->map(function ($date) use (&$res){
            $res[\Carbon\Carbon::parse($date['date'])->format('Y/m/d')] = $date['customData'];
        });
        return response()->json($res,200);
    }

    public function Rule(RuleRepository $Rule)
    {
        return response()->json($Rule->first()->only(['DefaultExtraBedPrice','DefaultExtraPeoplePrice']),200);
    }

    public function ExtraShopFromRoom(Request $request,RoomRepository $roomRepository)
    {
        $res = $roomRepository->getquery()->where('id',$request->Room)->first()->ExtraShops()->where('State',1)->orderBy('Sort','desc')->get([
            'extra_shops.id','Name','Src','Html','Price'
        ]);
        return response()->json($res,200);
    }

    public function ExtraCarFromRoom(Request $request,RoomRepository $roomRepository)
    {
        $res = $roomRepository->getquery()->where('id',$request->Room)->first()->ExtraCars()->where('State',1)->orderBy('Sort','desc')->get([
            'extra_cars.id','Name','Src','Html','Price','Price2','Max'
        ]);
        return response()->json($res,200);
    }

    public function CheckingDiscountCode(Request $request,DiscountCodeRepository $discountCodeRepository,LicenseRepository $licenseRepository)
    {
        $DiscountCode = new DiscountCode($discountCodeRepository,$licenseRepository);
        try {
            $res = $DiscountCode->CodeCheck($request->DiscountCode);
            return response()->json($res,200);
        }
        catch (\Exception $exception)
        {
            return  $this->FormatContract->customError('修改',[
                $exception->getMessage()
            ],400);
        }
    }

    /*
     * @todo 未完成 會員登入狀態
     * */
    public function CheckingOrder(CheckingOrderRequest $request)
    {
        //通過 基本 訂購人 入住人資料確認後
        //接者 確認訂單合法
        $OrderService = new Order(collect($request->BookingData),collect($request->form['DiscountCode']));
        \DB::beginTransaction();
        try {
            if(auth('member')->user()){
                $member = auth('member')->user()->id;
                $request->form['BookingSameGuest'] ? $Guest = collect($request->form['Booking']) :  $Guest = collect($request->form['Guest']);
                $Order = $OrderService->Create($member,collect($request->form['Booking']),$Guest,$request->form['TaxNumber'],$request->form['Note']);
                \DB::commit();
                if($member){
                    $MemberService = new \App\Service\Member();
                    $user = $MemberService->LoginById($member);

                    return response()->json([
                        'Member' => $user,
                        'Order' => $Order->Num
                    ],200);
                }
                else
                {
                    return response()->json([
                        'Order' => $Order->Num
                    ],200);
                }
            }
            else{
                $member = null;
                $request->form['BookingSameGuest'] ? $Guest = collect($request->form['Booking']) :  $Guest = collect($request->form['Guest']);

                if($request->form['BookingSameAuth'])
                {
                    if(Member::where('Email',$request->form['Booking']['Email'])->first()){
                        return  $this->FormatContract->customError('錯誤',[
                            '此信箱已申請過會員'
                        ],400);
                    }
                    else if(Member::where('IdNumber',$request->form['Booking']['IdNumber'])->first()){
                        return  $this->FormatContract->customError('錯誤',[
                            '此身份證已申請過會員'
                        ],400);
                    }

                    $NewMember= Member::Create([
                        'email' => $request->form['Booking']['Email'],
                        'password' => bcrypt($request->form['Booking']['IdNumber']),
                        'Name' => $request->form['Booking']['Name'],
                        'IdNumber' => $request->form['Booking']['IdNumber'],
                        'Phone' => $request->form['Booking']['Phone'],
                        'Area' => $request->form['Booking']['Area'],
                        'Sex' => $request->form['Booking']['Sex'],
                    ]);
                    $member = $NewMember->id;
                }

                $Order = $OrderService->Create($member,collect($request->form['Booking']),$Guest,$request->form['TaxNumber'],$request->form['Note']);
                \DB::commit();
                if($member){
                    $MemberService = new \App\Service\Member();
                    $user = $MemberService->LoginById($member);

                    return response()->json([
                        'Member' => $user,
                        'Order' => $Order->Num
                    ],200);
                }
                else
                {
                    return response()->json([
                        'Order' => $Order->Num
                    ],200);
                }
            }
        }
        catch (\Exception $exception)
        {
            \DB::rollback();
            return  $this->FormatContract->customError('錯誤',[
                $exception->getMessage()
            ],400);
        }

    }


    //都是找到該order 然後去取值
    public function PaymentSelect(OrderSearchRequest $request){
        try {
            $Order = new OrderData($request->only('Num'));
            $ResponseData = $Order->GetOrderDetail();
            return response()->json([
                'Order' => $ResponseData
            ],200);
        }
        catch (\Exception $exception){
            return  $this->FormatContract->customError('錯誤',[
                $exception->getMessage()
            ],400);
        }
    }

    public function UpdatePayment(Request $request){
        try {
            $Order = new OrderData($request->only('Num'));
            $Order->UpdatePayment($request->Payment);
            \Log::info('Update Success');
            return response()->json([],200);
        }
        catch (\Exception $exception){
            return  $this->FormatContract->customError('錯誤',[
                $exception->getMessage()
            ],400);
        }
    }

    public function ATMInfo()
    {
        $data = \App\ATMInfo::first()->only([
           'Html'
        ]);
        return response()->json($data);
    }

    public function Login(MemberLoginRequest $request){
        try{
            $MemberService = new \App\Service\Member();
            $user = $MemberService->Login($request);
            return response()->json($user);
        }
        catch (\Exception $exception)
        {
            return  $this->FormatContract->customError('錯誤',[
                $exception->getMessage()
            ],400);
        }
    }

    public function Register(MemberRegisterRequest $request){
        try{
            $MemberService = new \App\Service\Member();
            $NewMember = $MemberService->Create($request);

homete/resources/views/front/layouts/NewsArea.blade.php
@inject('NewsArea', 'App\Presenters\HomePresenter')
<div class="row NewsArea">
    <div class="col-lg-12 col-md-12 col-sm-12 NewsAreaBody" style="background: #f7f7f7;">
        <div data-aos="fade" data-aos-duration="2000">
            @foreach($NewsArea->getNews() as $news)
                <div class="col-lg-6 col-md-12 col-sm-12 pr-0 pl-0">
                    <div class="news_item">
                        <div class="NewsImg">
                            <a href="#">
                                <img src="{{ $news->Src }}" alt="">
                            </a>
                        </div>
                        <div class="NewsDate position-absolute text-center">
                            <div class="start">
                                <div class="month">
                                    {{ \Carbon\Carbon::parse($news->Start)->translatedFormat('M')}}
                                </div>
                                <div class="day">
                                    {{ \Carbon\Carbon::parse($news->Start)->translatedFormat('j')}}
                                </div>
                            </div>
                            @if($news->End)
                                <div class="end">
                                    <div class="month">
                                        {{ \Carbon\Carbon::parse($news->End)->translatedFormat('M')}}
                                    </div>
                                    <div class="day">
                                        {{ \Carbon\Carbon::parse($news->End)->translatedFormat('j')}}
                                    </div>
                                </div>
                            @endif
                        </div>
                        <div class="NewsText">
                            <div class="NewsSort">
                                {{ $news->Type->Title }}
                            </div>
                            <h3>
                                <a href="">
                                    {{ $news->Title }}
                                </a>
                            </h3>
                            {!! $news->Html !!}
                            <div class="NewsBtn">
                                <a href="" class="">More +</a>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>

homete/resources/views/front/layouts/RoomsArea.blade.php
@inject('RoomsArea', 'App\Presenters\HomePresenter')
<div class="row RoomsArea">
    <div class="col-md-12 p-0">
        <div class="RoomsTopImg">
            <div class="topimg">
                <img class="w-100" src="{{ $RoomsArea->getHomeRoom()->Src }}" alt="">
            </div>
        </div>
        <div class="sloganBox text-center" data-aos="fade-up" data-aos-duration="2000">
            <h1>{{ $RoomsArea->getHomeRoom()->Title }}</h1>
            <h2>{{ $RoomsArea->getHomeRoom()->Sub }}</h2>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-12 col-lg-offset-2 col-md-offset-0">
                <div class="owl-carousel RoomsBoxBody">
                    @foreach($RoomsArea->getRooms() as $room)
                        <div class="item">
                            <a href="#">
                                <div class="RoomsBox">
                                    <div class="Rooms_des">
                                        <a href="">
                                            <div class="Rooms_img">
                                                <img src="{{ $room->MainPicture }}" alt="">
                                            </div>
                                        </a>
                                        <div class="Rooms_text text-center">
                                            <a href="#">
                                                <h4>{{ $room->Name }}</h4>
                                            </a>
                                            <p class="RoomsBed mb-0">{{ $room->PeopleNumber }}人房</p>
                                            <p class="RoomsSize mb-0">約{{ $room->Ping }}坪</p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

    </div>
</div>

homete/resources/views/front/layouts/ShoppingCartFooter.blade.php
@extends('front.layouts.footer')
    @section('ShoppingCart')
        <shopping-cart></shopping-cart>
    @endsection

homete/resources/views/front/layouts/default.blade.php
@inject('default', 'App\Presenters\HomePresenter')
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $default->getSystem()->SiteName }}</title>
    <link rel="shortcut icon" href="{{ $default->getSystem()->Src }}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/d17564c281.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.9/css/weather-icons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/aos@2.3.0/dist/aos.css">
    <link rel="stylesheet" href="/css/front/fonts.css">
    <link rel='stylesheet' href='/css/front/daterangepicker.css'>
    <link rel='stylesheet' href='/css/front/eb.css'>
    <link rel='stylesheet' href='/css/front/eb-responsive.css'>
    <link rel='stylesheet' href='/css/front/rs6.css'>
    <link rel='stylesheet' href='/css/front/bootstrap.min.css'>
    <link rel='stylesheet' href='/css/front/animate.min.css'>
    <link rel="stylesheet" href="/css/front/owl.carousel.min.css">
    <link rel='stylesheet' href='/css/front/main.css'>
    <link rel='stylesheet' href='/css/front/responsive.css'>
    <script type="text/javascript" src='/js/front/jquery.js'></script>
    <script type="text/javascript" src='/js/front/jquery-migrate.min.js'></script>
</head>

<body data-rsssl=1 class="home page-template-default page page-id-60 wide wpb-js-composer js-comp-ver-6.2.0 vc_responsive">
<div id="loading">
    <div class="inner">
        <div class="loading_effect d-flex flex-column justify-content-center">
            <img src="{{ $default->getSystem()->Src }}" alt="">
            <div class="d-flex justify-content-center">
                <div class="object" id="object_one"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_three"></div>
            </div>
        </div>
    </div>
</div>
<div id="app">

<div class="wrapper">
    @yield('header')


    @yield('content')


    @yield('EventsArea')


    <div class="container-fluid">
        @yield('NewsArea')

        @yield('RoomsArea')
    </div>
</div>

@yield('footer')
</div>


</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/aos@2.3.0/dist/aos.js"></script>
<script type="text/javascript" src='/js/front/eb.js'></script>
<script type="text/javascript" src='/js/front/rbtools.min.js'></script>
<script type="text/javascript" src='/js/front/rs6.min.js'></script>
<script type="text/javascript" src='/js/front/bootstrap.min.js'></script>
<script type="text/javascript" src='/js/front/isotope.pkgd.min.js'></script>
<script type="text/javascript" src='/js/front/jPushMenu.js'></script>
<script type="text/javascript" src='/js/front/jquery.countdown.min.js'></script>
<script type="text/javascript" src='/js/front/jquery.magnific-popup.min.js'></script>
<script type="text/javascript" src='/js/front/moment.js'></script>
<script type="text/javascript" src='/js/front/daterangepicker.js'></script>
<script type="text/javascript" src='/js/front/ion.rangeslider.min.js'></script>
<script type="text/javascript" src='/js/front/wow.min.js'></script>
<script type="text/javascript" src='/js/front/main.js'></script>
<script type="text/javascript" src='/js/front/owl.carousel.min.js'></script>
<script type="text/javascript" src='/js/front/owl.carousel.thumbs.min.js'></script>
<script>
    AOS.init({})
</script>
@yield('js')

</html>

homete/resources/views/front/layouts/header.blade.php
@inject('Header', 'App\Presenters\HomePresenter')
<div class="top_menu">
    <div class="container">
        <ul class="top_menu_right">
            <li class="">
                <img src="https://img.icons8.com/ios/50/333333/ringer-volume.png" />
                <a href="tel:{{ $Header->getSystem()->Tel }}"> {{ $Header->getSystem()->Tel }}</a>
            </li>
            <li class="email ">
                <img src="https://img.icons8.com/ios/50/333333/open-envelope.png" />
                <a href="#">
                    <span class="email"> {{ $Header->getSystem()->Email }}</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<header class="fixed">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle mobile_menu_btn" data-toggle="collapse" data-target=".mobile_menu" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="mobile_member_btn" href="{{ route('front.login') }}">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30px" height="30px" viewBox="0 0 30 30" version="1.1">
                    <g id="Page-2" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="Iconscout-Header-New" transform="translate(-1293.000000, -108.000000)">
                            <g id="Group-18" transform="translate(70.000000, 83.000000)">
                                <g id="Group-17" transform="translate(20.000000, 18.000000)">
                                    <g id="Group-78-Copy" transform="translate(1196.000000, 0.000000)">
                                        <g id="Group-77">
                                            <g id="user" transform="translate(7.000000, 7.000000)">
                                                <g id="Layer_1">
                                                    <circle id="Oval" fill="transparent" cx="15" cy="15" r="14.2857143"/>
                                                    <path class="icon-body" d="M15,20.2380952 C10.8809524,20.2380952 7.19047619,21.9761905 4.57142857,24.7619048 C7.16666667,27.547619 10.8809524,29.2857143 15,29.2857143 C19.1190476,29.2857143 22.8095238,27.547619 25.4285714,24.7619048 C22.8095238,21.9761905 19.1190476,20.2380952 15,20.2380952 Z" id="Path" fill="#DEB667"/>
                                                    <path class="icon-border" d="M15,30 C10.8571429,30 6.88095238,28.2619048 4.04761905,25.2619048 C3.80952381,25 3.78571429,24.6190476 4,24.3333333 C4.02380952,24.3095238 4.02380952,24.2857143 4.04761905,24.2857143 C6.88095238,21.2619048 10.8809524,19.5238095 15,19.5238095 C17.9047619,19.5238095 20.7142857,20.3571429 23.1428571,21.9285714 C23.4761905,22.1428571 23.5714286,22.5952381 23.3571429,22.9285714 C23.1428571,23.2619048 22.6904762,23.3571429 22.3571429,23.1428571 C20.1904762,21.7142857 17.6190476,20.952381 15,20.952381 C11.4285714,20.952381 8.11904762,22.3095238 5.57142857,24.7619048 C8.11904762,27.2142857 11.4285714,28.5714286 15,28.5714286 C22.4761905,28.5714286 28.5714286,22.4761905 28.5714286,15 C28.5714286,7.52380952 22.4761905,1.42857143 15,1.42857143 C7.52380952,1.42857143 1.42857143,7.52380952 1.42857143,15 C1.42857143,17.1904762 1.95238095,19.3809524 2.97619048,21.3095238 C3.16666667,21.6666667 3.02380952,22.0952381 2.66666667,22.2857143 C2.30952381,22.4761905 1.88095238,22.3333333 1.69047619,21.9761905 C0.595238095,19.8333333 0,17.4285714 0,15 C0,6.73809524 6.73809524,0 15,0 C23.2619048,0 30,6.73809524 30,15 C30,23.2619048 23.2619048,30 15,30 Z" id="Path" fill="#DEB667"/>
                                                    <path d="M15,5.71428571 C11.8571429,5.71428571 9.28571429,8.28571429 9.28571429,11.4285714 C9.28571429,14.5714286 11.8571429,17.1428571 15,17.1428571 C18.1428571,17.1428571 20.7142857,14.5714286 20.7142857,11.4285714 C20.7142857,8.28571429 18.1428571,5.71428571 15,5.71428571 Z" id="Path" fill="#DEB667"/>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </a>

            <a class="navbar-brand light" href="{{ route('front.index') }}">
                <img src="{{ $Header->getSystem()->Src }}" height="45">
            </a>
            <a class="navbar-brand dark nodisplay" href="{{ route('front.index') }}">
                <img src="{{ $Header->getSystem()->Src }}" height="45">
            </a>
        </div>
        <nav id="main_menu" class="mobile_menu navbar-collapse">
            <ul id="menu-main-menu" class="nav navbar-nav">
                <li class="mobile_menu_title" style="display:none;">Menu</li>
                @foreach($Header->getSubject() as $subject)
                    @switch($subject->Tag)
                        @case('about')
                        @case('news')
                        @case('traffic')
                            <li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{{ route('front.'.$subject->Tag) }}">{{ $subject->Name }}</a></li>
                            @break
                        @case('rooms')
                        <li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="rooms.html">房型介紹</a></li>
                            @break
                        @default
                            <li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="rooms.html">{{ $subject->Name }}</a></li>
                    @endswitch
                @endforeach

                <li class="menu-item menu-item-type-post_type_archive menu-item-object-hotel_rooms menu-item-has-children dropdown language d-lg-block d-md-none d-none">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle" >中 <span class="arrow mobile-dropdown-toggle"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        @foreach($Header->getLocale() as $locale)
                            <li class="menu-item menu-item-type-post_type_archive menu-item-object-hotel_rooms"><a href="#">{{ $locale->Name }}</a></li>
                        @endforeach
                    </ul>
                </li>

                <li class="menu_button"><a href="{{route('front.booking')}}" class="btn eb-btn" target="_self"><img src="https://img.icons8.com/ios/25/ffffff/today.png" />立即訂房</a></li>
                <li class="member-btn d-lg-block d-md-none d-none">
                    <a href="{{route('front.login')}}">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30px" height="30px" viewBox="0 0 30 30" version="1.1">
                            <g id="Page-2" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <g id="Iconscout-Header-New" transform="translate(-1293.000000, -108.000000)">
                                    <g id="Group-18" transform="translate(70.000000, 83.000000)">
                                        <g id="Group-17" transform="translate(20.000000, 18.000000)">
                                            <g id="Group-78-Copy" transform="translate(1196.000000, 0.000000)">
                                                <g id="Group-77">
                                                    <g id="user" transform="translate(7.000000, 7.000000)">
                                                        <g id="Layer_1">
                                                            <circle id="Oval" fill="transparent" cx="15" cy="15" r="14.2857143"/>
                                                            <path class="icon-body" d="M15,20.2380952 C10.8809524,20.2380952 7.19047619,21.9761905 4.57142857,24.7619048 C7.16666667,27.547619 10.8809524,29.2857143 15,29.2857143 C19.1190476,29.2857143 22.8095238,27.547619 25.4285714,24.7619048 C22.8095238,21.9761905 19.1190476,20.2380952 15,20.2380952 Z" id="Path"/>
                                                            <path class="icon-border" d="M15,30 C10.8571429,30 6.88095238,28.2619048 4.04761905,25.2619048 C3.80952381,25 3.78571429,24.6190476 4,24.3333333 C4.02380952,24.3095238 4.02380952,24.2857143 4.04761905,24.2857143 C6.88095238,21.2619048 10.8809524,19.5238095 15,19.5238095 C17.9047619,19.5238095 20.7142857,20.3571429 23.1428571,21.9285714 C23.4761905,22.1428571 23.5714286,22.5952381 23.3571429,22.9285714 C23.1428571,23.2619048 22.6904762,23.3571429 22.3571429,23.1428571 C20.1904762,21.7142857 17.6190476,20.952381 15,20.952381 C11.4285714,20.952381 8.11904762,22.3095238 5.57142857,24.7619048 C8.11904762,27.2142857 11.4285714,28.5714286 15,28.5714286 C22.4761905,28.5714286 28.5714286,22.4761905 28.5714286,15 C28.5714286,7.52380952 22.4761905,1.42857143 15,1.42857143 C7.52380952,1.42857143 1.42857143,7.52380952 1.42857143,15 C1.42857143,17.1904762 1.95238095,19.3809524 2.97619048,21.3095238 C3.16666667,21.6666667 3.02380952,22.0952381 2.66666667,22.2857143 C2.30952381,22.4761905 1.88095238,22.3333333 1.69047619,21.9761905 C0.595238095,19.8333333 0,17.4285714 0,15 C0,6.73809524 6.73809524,0 15,0 C23.2619048,0 30,6.73809524 30,15 C30,23.2619048 23.2619048,30 15,30 Z" id="Path"/>
                                                            <path class="icon-head" d="M15,5.71428571 C11.8571429,5.71428571 9.28571429,8.28571429 9.28571429,11.4285714 C9.28571429,14.5714286 11.8571429,17.1428571 15,17.1428571 C18.1428571,17.1428571 20.7142857,14.5714286 20.7142857,11.4285714 C20.7142857,8.28571429 18.1428571,5.71428571 15,5.71428571 Z" id="Path"/>
                                                        </g>
                                                    </g>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                </g>
                            </g>
                        </svg>
                    </a>
                </li>
                <li class="mobile_menu_language pt-5 mt-2">
                    <div class="d-flex justify-content-center font-13">
                        @foreach($Header->getLocale() as $locale)
                            <a href="">{{$locale->Name}}</a>
                        @endforeach
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</header>